server:
  port: 80

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://192.168.2.100:3306/security_demo?useUnicode=true&characterEncoding=utf8mb4
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: hnwz86505002

mybatis:
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名转换
